
name: 'NSO in Docker'

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NSO_VERSION: 5.4
    container:
      image: registry.gitlab.com/nso-developer/ci-runner-image:latest

    steps:
      - uses: actions/checkout@v1
      - uses: prewk/s3-cp-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE: s3://nso-install-files/nso-${NSO_VERSION}.linux.x86_64.installer.bin
          DEST: nso-install-files/nso-${NSO_VERSION}.linux.x86_64.installer.bin
      - name: 'Building base and dev image'
        run: make build
      - name: 'Testing images'
        run: make test
